### ISSUE TITLE
YesAlready freezing FFXIV

### ISSUE THREAD

**Issue by maxrmax** [PunishXIV/YesAlready#132]
Hello,

i have for a while the issue that YesAlready is freezing my entire FFXIV.
It took me a while to bring it down to the issue being this plugin.

The freeze can happen on any Yes / No prompt.
Return, Discard, putting items in or out of glamour dresser.
The location doesn't matter and it can happen on the first prompt after boot or when you want to log out/exit the game after a longer session.

Enabled settings:
YesNo:
- Auto GimmickYesNo
Bothers:
- MaterializeDialog
Settings:
- DTR

The freeze happens even with minimal options enabled.
```
[ERR] [AddonLifecycle] Exception in OnAddonFinalize during PreFinalize invoke.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at YesAlready.Features.AddonSelectStringFeature.SetEntry(AddonEvent type, AddonArgs args) in C:\Users\snow\Documents\Code\FFXIV Plugins\YesAlready\YesAlready\Features\AddonSelectStringFeature.cs:line 21
   at Dalamud.Game.Addon.Lifecycle.AddonLifecycle.InvokeListenersSafely(AddonEvent eventType, AddonArgs args, String blame) in C:\goatsoft\companysecrets\dalamud\\Game\Addon\Lifecycle\AddonLifecycle.cs:line 170
```
Both paths do not belong to me or my pc but are inside the dalamud.log
This is the log entry right for the freeze.

I would love to get this issue resolved and if any help is necessary even help.
I would provide YesAlready logs but i found no way to enable extra logging for the plugin.

**Comment by Jaksuhn** [comment]
stale, pretty sure this was fixed at some point
