### ISSUE TITLE
YesAlready plugin failed to load.

### ISSUE THREAD

**Issue by FPTK** [PunishXIV/YesAlready#137]
I am encountering an issue while trying to load the YesAlready plugin. The plugin fails to initialize and throws the following error:

2024-11-30 20:42:07.419 +08:00 [INF] [PLUGINM] Loading plugin Yes Already
2024-11-30 20:42:07.420 +08:00 [WRN] [PROFMAN] '"fd8575fd-8bbe-46d1-b33b-61895ec5e7aa"'('YesAlready') was not in any profile, adding to default with true
2024-11-30 20:42:07.421 +08:00 [INF] [PROFILE] Adding plugin YesAlready("fd8575fd-8bbe-46d1-b33b-61895ec5e7aa") to profile "00000000-0000-0000-0000-000000000000" with state true
2024-11-30 20:42:07.421 +08:00 [INF] [PLUGINM] YesAlready defaultState: true wantedByAnyProfile: true loadPlugin: true
2024-11-30 20:42:07.421 +08:00 [INF] [LOCALPLUGIN] Loading YesAlready.dll
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: You must install .NET to run this application.
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: 
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: App: C:\Users\Eureka\AppData\Roaming\XIVLauncherCN\installedPlugins\Browsingway\1.6.2\renderer\Browsingway.Renderer.exe
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: Architecture: x64
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: App host version: 8.0.0
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: .NET location: Not found
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: 
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: Learn more:
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: https://aka.ms/dotnet/app-launch-failed
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: 
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: Download the .NET runtime:
2024-11-30 20:42:07.509 +08:00 [ERR] [Browsingway] [Render]: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win-x64&os=win10&apphost_version=8.0.0
2024-11-30 20:42:07.511 +08:00 [ERR] [Browsingway] [Render]: 
2024-11-30 20:42:07.511 +08:00 [INF] [Browsingway] [Render]: 
2024-11-30 20:42:07.518 +08:00 [ERR] [Browsingway] Render process crashed - will restart asap
2024-11-30 20:42:07.573 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0xMS0zMFQyMDo0MjowNy41NzE5MDE5KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlJlZmxlY3Rpb25UeXBlTG9hZEV4Y2VwdGlvbjogVW5hYmxlIHRvIGxvYWQgb25lIG9yIG1vcmUgb2YgdGhlIHJlcXVlc3RlZCB0eXBlcy5cclxuQ291bGQgbm90IGxvYWQgdHlwZSAnTHVtaW5hLkV4Y2VsLlNoZWV0cy5JdGVtJyBmcm9tIGFzc2VtYmx5ICdMdW1pbmEuRXhjZWwsIFZlcnNpb249Ny4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsJy5cclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uUnVudGltZU1vZHVsZS5HZXRUeXBlcyhSdW50aW1lTW9kdWxlIG1vZHVsZSlcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uUnVudGltZU1vZHVsZS5HZXRUeXBlcygpXHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlR5cGVzLkxvY2FsUGx1Z2luLkVuc3VyZUxvYWRlcigpXHJcblN5c3RlbS5UeXBlTG9hZEV4Y2VwdGlvbjogQ291bGQgbm90IGxvYWQgdHlwZSAnTHVtaW5hLkV4Y2VsLlNoZWV0cy5JdGVtJyBmcm9tIGFzc2VtYmx5ICdMdW1pbmEuRXhjZWwsIFZlcnNpb249Ny4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsJy4iLCJDb250ZXh0IjoiW0xPQ0FMUExVR0lOXSBDb3VsZCBub3QgbG9hZCBvbmUgb3IgbW9yZSB0eXBlcyB3aGVuIHNlYXJjaGluZyBmb3IgSURhbGFtdWRQbHVnaW46IEM6XFxVc2Vyc1xcRXVyZWthXFxBcHBEYXRhXFxSb2FtaW5nXFxYSVZMYXVuY2hlckNOXFxpbnN0YWxsZWRQbHVnaW5zXFxZZXNBbHJlYWR5XFwxLjguOFxcWWVzQWxyZWFkeS5kbGwifQ==
2024-11-30 20:42:07.563 +08:00 [ERR] [LOCALPLUGIN] Could not load one or more types when searching for IDalamudPlugin: C:\Users\Eureka\AppData\Roaming\XIVLauncherCN\installedPlugins\YesAlready\1.8.8\YesAlready.dll
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Lumina.Excel.Sheets.Item' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Dalamud.Plugin.Internal.Types.LocalPlugin.EnsureLoader()
System.TypeLoadException: Could not load type 'Lumina.Excel.Sheets.Item' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: You must install .NET to run this application.
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: 
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: App: C:\Users\Eureka\AppData\Roaming\XIVLauncherCN\installedPlugins\Browsingway\1.6.2\renderer\Browsingway.Renderer.exe
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: Architecture: x64
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: App host version: 8.0.0
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: .NET location: Not found
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: 
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: Learn more:
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: https://aka.ms/dotnet/app-launch-failed
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: 
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: Download the .NET runtime:
2024-11-30 20:42:07.605 +08:00 [ERR] [Browsingway] [Render]: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win-x64&os=win10&apphost_version=8.0.0
2024-11-30 20:42:07.607 +08:00 [ERR] [Browsingway] [Render]: 
2024-11-30 20:42:07.607 +08:00 [INF] [Browsingway] [Render]: 
2024-11-30 20:42:07.621 +08:00 [ERR] [Browsingway] Render process crashed - will restart asap
2024-11-30 20:42:07.692 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0xMS0zMFQyMDo0MjowNy42OTIxMjg4KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5BZ2dyZWdhdGVFeGNlcHRpb246IEZhaWxlZCB0byBjcmVhdGUgWWVzQWxyZWFkeS5ZZXNBbHJlYWR5IChjdG9yIGludm9jYXRpb24pIChFeGNlcHRpb24gaGFzIGJlZW4gdGhyb3duIGJ5IHRoZSB0YXJnZXQgb2YgYW4gaW52b2NhdGlvbi4pXHJcbiAtLS0+IFN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uVHlwZUxvYWRFeGNlcHRpb246IENvdWxkIG5vdCBsb2FkIHR5cGUgJ0x1bWluYS5FeGNlbC5JRXhjZWxSb3dgMScgZnJvbSBhc3NlbWJseSAnTHVtaW5hLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbCcuXHJcbiAgIGF0IEVDb21tb25zLkVDb21tb25zTWFpbi5Jbml0KElEYWxhbXVkUGx1Z2luSW50ZXJmYWNlIHBsdWdpbkludGVyZmFjZSwgSURhbGFtdWRQbHVnaW4gaW5zdGFuY2UsIE1vZHVsZVtdIG1vZHVsZXMpXHJcbiAgIGF0IFllc0FscmVhZHkuWWVzQWxyZWFkeS4uY3RvcihJRGFsYW11ZFBsdWdpbkludGVyZmFjZSBwbHVnaW5JbnRlcmZhY2UpIGluIC9ob21lL3J1bm5lci93b3JrL1llc0FscmVhZHkvWWVzQWxyZWFkeS9ZZXNBbHJlYWR5L1llc0FscmVhZHkuY3M6bGluZSA0OVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZU1ldGhvZEhhbmRsZS5JbnZva2VNZXRob2QoT2JqZWN0IHRhcmdldCwgVm9pZCoqIGFyZ3VtZW50cywgU2lnbmF0dXJlIHNpZywgQm9vbGVhbiBpc0NvbnN0cnVjdG9yKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5NZXRob2RCYXNlSW52b2tlci5JbnZva2VDb25zdHJ1Y3RvcldpdGhvdXRBbGxvYyhPYmplY3Qgb2JqLCBCaW5kaW5nRmxhZ3MgaW52b2tlQXR0ciwgQmluZGVyIGJpbmRlciwgT2JqZWN0W10gcGFyYW1ldGVycywgQ3VsdHVyZUluZm8gY3VsdHVyZSlcclxuICAgLS0tIEVuZCBvZiBpbm5lciBleGNlcHRpb24gc3RhY2sgdHJhY2UgLS0tXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLk1ldGhvZEJhc2VJbnZva2VyLkludm9rZUNvbnN0cnVjdG9yV2l0aG91dEFsbG9jKE9iamVjdCBvYmosIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5NZXRob2RCYXNlLkludm9rZShPYmplY3Qgb2JqLCBPYmplY3RbXSBwYXJhbWV0ZXJzKVxyXG4gICBhdCBEYWxhbXVkLklvQy5JbnRlcm5hbC5TZXJ2aWNlQ29udGFpbmVyLjw+Y19fRGlzcGxheUNsYXNzMTBfMC48Q3JlYXRlQXN5bmM+Yl9fMCgpXHJcbi0tLSBFbmQgb2Ygc3RhY2sgdHJhY2UgZnJvbSBwcmV2aW91cyBsb2NhdGlvbiAtLS1cclxuICAgYXQgRGFsYW11ZC5Jb0MuSW50ZXJuYWwuU2VydmljZUNvbnRhaW5lci5DcmVhdGVBc3luYyhUeXBlIG9iamVjdFR5cGUsIE9iamVjdFtdIHNjb3BlZE9iamVjdHMsIElTZXJ2aWNlU2NvcGUgc2NvcGUpXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBEYWxhbXVkLklvQy5JbnRlcm5hbC5TZXJ2aWNlQ29udGFpbmVyLkNyZWF0ZUFzeW5jKFR5cGUgb2JqZWN0VHlwZSwgT2JqZWN0W10gc2NvcGVkT2JqZWN0cywgSVNlcnZpY2VTY29wZSBzY29wZSlcclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuVHlwZXMuTG9jYWxQbHVnaW4uPD5jX19EaXNwbGF5Q2xhc3M3NV8wLjw8Q3JlYXRlUGx1Z2luSW5zdGFuY2U+Z19fQ3JlYXRlfDA+ZC5Nb3ZlTmV4dCgpXHJcbi0tLSBFbmQgb2Ygc3RhY2sgdHJhY2UgZnJvbSBwcmV2aW91cyBsb2NhdGlvbiAtLS1cclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuVHlwZXMuTG9jYWxQbHVnaW4uQ3JlYXRlUGx1Z2luSW5zdGFuY2UoTG9jYWxQbHVnaW5NYW5pZmVzdCBtYW5pZmVzdCwgSVNlcnZpY2VTY29wZSBzY29wZSwgVHlwZSB0eXBlLCBEYWxhbXVkUGx1Z2luSW50ZXJmYWNlIGRhbGFtdWRJbnRlcmZhY2UpXHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlR5cGVzLkxvY2FsUGx1Z2luLkxvYWRBc3luYyhQbHVnaW5Mb2FkUmVhc29uIHJlYXNvbiwgQm9vbGVhbiByZWxvYWRpbmcpIiwiQ29udGV4dCI6IltMT0NBTFBMVUdJTl0gRXJyb3Igd2hpbGUgbG9hZGluZyBcIlllc0FscmVhZHlcIiwgZmFpbGVkIHRvIGJpbmQgYW5kIGNhbGwgdGhlIHBsdWdpbiBjb25zdHJ1Y3RvciJ9
2024-11-30 20:42:07.689 +08:00 [ERR] [LOCALPLUGIN] Error while loading YesAlready, failed to bind and call the plugin constructor
System.AggregateException: Failed to create YesAlready.YesAlready (ctor invocation) (Exception has been thrown by the target of an invocation.)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'Lumina.Excel.IExcelRow`1' from assembly 'Lumina, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ECommons.ECommonsMain.Init(IDalamudPluginInterface pluginInterface, IDalamudPlugin instance, Module[] modules)
   at YesAlready.YesAlready..ctor(IDalamudPluginInterface pluginInterface) in /home/runner/work/YesAlready/YesAlready/YesAlready/YesAlready.cs:line 49
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0()
--- End of stack trace from previous location ---
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope)
   --- End of inner exception stack trace ---
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope)
   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass75_0.<<CreatePluginInstance>g__Create|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dalamud.Plugin.Internal.Types.LocalPlugin.CreatePluginInstance(LocalPluginManifest manifest, IServiceScope scope, Type type, DalamudPluginInterface dalamudInterface)
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading)

can you help me to solve this problem

**Comment by Jaksuhn** [comment]
you are either on CN or you have an incredibly broken dalamud

**Comment by FPTK** [comment]
> you are either on CN or you have an incredibly broken dalamud

yes I'm on CN and I solve this problem by downloading a lower version yesalready(the latest one's api is too high), thank you for your reply.
